development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: your_app_production
  polling_interval: 0.1.seconds
  message_retention: 1.day
